name: Gitee Pages Action

on: page_build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE }}
        with:
          source-repo: git@github.com:Kaiyiwing/qwerty-learner.git
          destination-repo: git@gitee.com:KaiyiWing/qwerty-learner.git
